language: node_js
sudo: required
node_js:
  - "stable"
# travis call prepare 
# create the minify version
before_install:
   - cd ../
   - git clone https://github.com/terminusdb/terminus-client.git
   - cd  terminus-client
   - git checkout dev
   - npm install 
   - cd terminus-dashboard

after_script: "npm run build:all"

branches:
  only:
    - dev
    - master